// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentService exposes local LaTeX environment setup operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckLatexEnvironment(): $CancellablePromise<$models.LatexEnvironmentDTO | null> {
    return $Call.ByID(3612829077).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DownloadTexLiveInstaller(variant: string): $CancellablePromise<$models.TexLiveDownloadDTO | null> {
    return $Call.ByID(204430237, variant).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ReloadLatexEnvironment(): $CancellablePromise<$models.LatexEnvironmentDTO | null> {
    return $Call.ByID(4054225300).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartTexLiveInstaller(variant: string): $CancellablePromise<$models.TexLiveDownloadDTO | null> {
    return $Call.ByID(3486878313, variant).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LatexEnvironmentDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TexLiveDownloadDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
