// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CompileResult contains the PDF bytes and compiler log returned to the UI.
 */
export class CompileResult {
    "pdf": string;
    "log": string;

    /** Creates a new CompileResult instance. */
    constructor($$source: Partial<CompileResult> = {}) {
        if (!("pdf" in $$source)) {
            this["pdf"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompileResult {
        const $$createField0_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pdf" in $$parsedSource) {
            $$parsedSource["pdf"] = $$createField0_0($$parsedSource["pdf"]);
        }
        return new CompileResult($$parsedSource as Partial<CompileResult>);
    }
}

/**
 * DiffResultDTO 包装两个历史版本间的 unified diff 文本。
 */
export class DiffResultDTO {
    "diff": string;

    /** Creates a new DiffResultDTO instance. */
    constructor($$source: Partial<DiffResultDTO> = {}) {
        if (!("diff" in $$source)) {
            this["diff"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffResultDTO($$parsedSource as Partial<DiffResultDTO>);
    }
}

/**
 * FileDTO is the file shape exposed to Wails bindings.
 */
export class FileDTO {
    "id": number;
    "project_id": number;
    "parent_id": number | null;
    "name": string;
    "is_dir": boolean;
    "content"?: string;
    "created_at": string;
    "updated_at": string;
    "children"?: (FileDTO | null)[];

    /** Creates a new FileDTO instance. */
    constructor($$source: Partial<FileDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDTO {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField8_0($$parsedSource["children"]);
        }
        return new FileDTO($$parsedSource as Partial<FileDTO>);
    }
}

/**
 * FileRevisionDTO 是文件历史版本的对外结构。
 */
export class FileRevisionDTO {
    "id": number;
    "project_id": number;
    "file_id": number;
    "file_path": string;
    "content_hash": string;
    "size": number;
    "reason": string;
    "snapshot_id"?: number | null;
    "created_at": string;

    /** Creates a new FileRevisionDTO instance. */
    constructor($$source: Partial<FileRevisionDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("file_id" in $$source)) {
            this["file_id"] = 0;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("content_hash" in $$source)) {
            this["content_hash"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileRevisionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FileRevisionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileRevisionDTO($$parsedSource as Partial<FileRevisionDTO>);
    }
}

export class LatexEnvironmentDTO {
    "compiler": string;
    "has_compiler": boolean;
    "tools": LatexToolDTO[];

    /** Creates a new LatexEnvironmentDTO instance. */
    constructor($$source: Partial<LatexEnvironmentDTO> = {}) {
        if (!("compiler" in $$source)) {
            this["compiler"] = "";
        }
        if (!("has_compiler" in $$source)) {
            this["has_compiler"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatexEnvironmentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatexEnvironmentDTO {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField2_0($$parsedSource["tools"]);
        }
        return new LatexEnvironmentDTO($$parsedSource as Partial<LatexEnvironmentDTO>);
    }
}

export class LatexToolDTO {
    "name": string;
    "path": string;
    "version": string;
    "available": boolean;

    /** Creates a new LatexToolDTO instance. */
    constructor($$source: Partial<LatexToolDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatexToolDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatexToolDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatexToolDTO($$parsedSource as Partial<LatexToolDTO>);
    }
}

/**
 * ProjectDTO is the project shape exposed to Wails bindings.
 */
export class ProjectDTO {
    "id": number;
    "name": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ProjectDTO instance. */
    constructor($$source: Partial<ProjectDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectDTO($$parsedSource as Partial<ProjectDTO>);
    }
}

/**
 * ProjectSnapshotDTO 是项目快照的对外结构。
 */
export class ProjectSnapshotDTO {
    "id": number;
    "project_id": number;
    "reason": string;
    "file_count": number;
    "total_size": number;
    "snapshot_of": string;
    "created_at": string;

    /** Creates a new ProjectSnapshotDTO instance. */
    constructor($$source: Partial<ProjectSnapshotDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("file_count" in $$source)) {
            this["file_count"] = 0;
        }
        if (!("total_size" in $$source)) {
            this["total_size"] = 0;
        }
        if (!("snapshot_of" in $$source)) {
            this["snapshot_of"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSnapshotDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSnapshotDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectSnapshotDTO($$parsedSource as Partial<ProjectSnapshotDTO>);
    }
}

/**
 * RevisionContentDTO 包装某个历史版本的完整内容。
 */
export class RevisionContentDTO {
    "content": string;

    /** Creates a new RevisionContentDTO instance. */
    constructor($$source: Partial<RevisionContentDTO> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevisionContentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RevisionContentDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RevisionContentDTO($$parsedSource as Partial<RevisionContentDTO>);
    }
}

/**
 * SynctexEditDTO 是反向同步（PDF → 源码）结果。
 */
export class SynctexEditDTO {
    "input": string;
    "line": number;
    "column": number;
    "offset": number;

    /** Creates a new SynctexEditDTO instance. */
    constructor($$source: Partial<SynctexEditDTO> = {}) {
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SynctexEditDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SynctexEditDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SynctexEditDTO($$parsedSource as Partial<SynctexEditDTO>);
    }
}

/**
 * SynctexViewDTO 是正向同步（源码 → PDF）结果。
 */
export class SynctexViewDTO {
    "page": number;
    "x": number;
    "y": number;
    "h": number;
    "v": number;
    "w": number;
    "height": number;

    /** Creates a new SynctexViewDTO instance. */
    constructor($$source: Partial<SynctexViewDTO> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }
        if (!("v" in $$source)) {
            this["v"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SynctexViewDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SynctexViewDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SynctexViewDTO($$parsedSource as Partial<SynctexViewDTO>);
    }
}

export class TexLiveDownloadDTO {
    "variant": string;
    "scheme": string;
    "url": string;
    "installer_path": string;
    "install_args": string[];
    "already_exists": boolean;
    "size": number;

    /** Creates a new TexLiveDownloadDTO instance. */
    constructor($$source: Partial<TexLiveDownloadDTO> = {}) {
        if (!("variant" in $$source)) {
            this["variant"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("installer_path" in $$source)) {
            this["installer_path"] = "";
        }
        if (!("install_args" in $$source)) {
            this["install_args"] = [];
        }
        if (!("already_exists" in $$source)) {
            this["already_exists"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TexLiveDownloadDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TexLiveDownloadDTO {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("install_args" in $$parsedSource) {
            $$parsedSource["install_args"] = $$createField4_0($$parsedSource["install_args"]);
        }
        return new TexLiveDownloadDTO($$parsedSource as Partial<TexLiveDownloadDTO>);
    }
}

// Private type creation functions
const $$createType0 = FileDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LatexToolDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
