// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CompileResult contains the PDF bytes and compiler log returned to the UI.
 */
export class CompileResult {
    "pdf": string;
    "log": string;

    /** Creates a new CompileResult instance. */
    constructor($$source: Partial<CompileResult> = {}) {
        if (!("pdf" in $$source)) {
            this["pdf"] = "";
        }
        if (!("log" in $$source)) {
            this["log"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompileResult {
        const $$createField0_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pdf" in $$parsedSource) {
            $$parsedSource["pdf"] = $$createField0_0($$parsedSource["pdf"]);
        }
        return new CompileResult($$parsedSource as Partial<CompileResult>);
    }
}

/**
 * FileDTO is the file shape exposed to Wails bindings.
 */
export class FileDTO {
    "id": number;
    "project_id": number;
    "parent_id": number | null;
    "name": string;
    "is_dir": boolean;
    "content"?: string;
    "created_at": string;
    "updated_at": string;
    "children"?: (FileDTO | null)[];

    /** Creates a new FileDTO instance. */
    constructor($$source: Partial<FileDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDTO {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField8_0($$parsedSource["children"]);
        }
        return new FileDTO($$parsedSource as Partial<FileDTO>);
    }
}

export class LatexEnvironmentDTO {
    "compiler": string;
    "has_compiler": boolean;
    "tools": LatexToolDTO[];

    /** Creates a new LatexEnvironmentDTO instance. */
    constructor($$source: Partial<LatexEnvironmentDTO> = {}) {
        if (!("compiler" in $$source)) {
            this["compiler"] = "";
        }
        if (!("has_compiler" in $$source)) {
            this["has_compiler"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatexEnvironmentDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatexEnvironmentDTO {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField2_0($$parsedSource["tools"]);
        }
        return new LatexEnvironmentDTO($$parsedSource as Partial<LatexEnvironmentDTO>);
    }
}

export class LatexToolDTO {
    "name": string;
    "path": string;
    "version": string;
    "available": boolean;

    /** Creates a new LatexToolDTO instance. */
    constructor($$source: Partial<LatexToolDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatexToolDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LatexToolDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatexToolDTO($$parsedSource as Partial<LatexToolDTO>);
    }
}

/**
 * ProjectDTO is the project shape exposed to Wails bindings.
 */
export class ProjectDTO {
    "id": number;
    "name": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ProjectDTO instance. */
    constructor($$source: Partial<ProjectDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectDTO($$parsedSource as Partial<ProjectDTO>);
    }
}

export class TexLiveDownloadDTO {
    "variant": string;
    "scheme": string;
    "url": string;
    "installer_path": string;
    "install_args": string[];
    "already_exists": boolean;
    "size": number;

    /** Creates a new TexLiveDownloadDTO instance. */
    constructor($$source: Partial<TexLiveDownloadDTO> = {}) {
        if (!("variant" in $$source)) {
            this["variant"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("installer_path" in $$source)) {
            this["installer_path"] = "";
        }
        if (!("install_args" in $$source)) {
            this["install_args"] = [];
        }
        if (!("already_exists" in $$source)) {
            this["already_exists"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TexLiveDownloadDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TexLiveDownloadDTO {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("install_args" in $$parsedSource) {
            $$parsedSource["install_args"] = $$createField4_0($$parsedSource["install_args"]);
        }
        return new TexLiveDownloadDTO($$parsedSource as Partial<TexLiveDownloadDTO>);
    }
}

// Private type creation functions
const $$createType0 = FileDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LatexToolDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
