// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService exposes project operations to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProject(name: string): $CancellablePromise<$models.ProjectDTO | null> {
    return $Call.ByID(2423167141, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteProject(id: number): $CancellablePromise<void> {
    return $Call.ByID(3569767356, id);
}

export function GetProject(id: number): $CancellablePromise<$models.ProjectDTO | null> {
    return $Call.ByID(2743552853, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectDTO[]> {
    return $Call.ByID(2928992966).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateProject(id: number, name: string): $CancellablePromise<$models.ProjectDTO | null> {
    return $Call.ByID(3599361422, id, name).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProjectDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
