name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "goleaf-linux-amd64"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "goleaf-windows-amd64"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "goleaf-macos"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
