// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompileProject(arg1) {
  return window['go']['transport']['App']['CompileProject'](arg1);
}

export function CreateFile(arg1, arg2, arg3, arg4) {
  return window['go']['transport']['App']['CreateFile'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1) {
  return window['go']['transport']['App']['CreateProject'](arg1);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['transport']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['transport']['App']['DeleteProject'](arg1);
}

export function GetFileContent(arg1, arg2) {
  return window['go']['transport']['App']['GetFileContent'](arg1, arg2);
}

export function GetFileTree(arg1) {
  return window['go']['transport']['App']['GetFileTree'](arg1);
}

export function GetProject(arg1) {
  return window['go']['transport']['App']['GetProject'](arg1);
}

export function ListProjects() {
  return window['go']['transport']['App']['ListProjects']();
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['transport']['App']['RenameFile'](arg1, arg2, arg3);
}

export function UpdateFileContent(arg1, arg2, arg3) {
  return window['go']['transport']['App']['UpdateFileContent'](arg1, arg2, arg3);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['transport']['App']['UpdateProject'](arg1, arg2);
}
