// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';

export function CompileProject(arg1:number):Promise<transport.CompileResult>;

export function CreateFile(arg1:number,arg2:string,arg3:any,arg4:boolean):Promise<transport.FileDTO>;

export function CreateProject(arg1:string):Promise<transport.ProjectDTO>;

export function DeleteFile(arg1:number,arg2:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetFileContent(arg1:number,arg2:number):Promise<transport.FileDTO>;

export function GetFileTree(arg1:number):Promise<Array<transport.FileDTO>>;

export function GetProject(arg1:number):Promise<transport.ProjectDTO>;

export function ListProjects():Promise<Array<transport.ProjectDTO>>;

export function RenameFile(arg1:number,arg2:number,arg3:string):Promise<transport.FileDTO>;

export function UpdateFileContent(arg1:number,arg2:number,arg3:string):Promise<transport.FileDTO>;

export function UpdateProject(arg1:number,arg2:string):Promise<transport.ProjectDTO>;
